### ISSUE TITLE
Crash on running( Segmentation fault (core dumped) )

### ISSUE THREAD

**Issue by ST-Chara** [headshot2017/ddnet-sm64#1]
Segmentation fault (core dumped)

Thread 1 "DDNet-Server" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ea15e3 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) bt
#0  0x00007ffff7ea15e3 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007ffff7ea240b in SHA1_Update () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x00007ffff7ea2298 in SHA1 () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x000055555558fca0 in CServer::Run (this=0x7ffff49f1010) at /home/lighthouse/fastgit/src/engine/server/server.cpp:2647
#4  0x000055555557586c in main (argc=1, argv=0x7fffffffe4f8) at /home/lighthouse/fastgit/src/engine/server/main.cpp:187

System: Ubuntu 20.04 Server
1 Core 50GB
[ROM link removed]()

**Comment by headshot2017** [comment]
> System: Ubuntu 20.04 Server 1 Core 50GB sm64.us.z64.zip
please remove the rom attachment

**Comment by headshot2017** [comment]
please do not upload the rom in the future

**Comment by ST-Chara** [comment]
Next crash(

Thread 1 "DDNet-Server" received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:384
384     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:384
#1  0x00007ffff7a3d4cd in sm64_global_init (rom=0x7fffdb841010 "\200\067\022@", outTexture=0x55555598f0e0 "", 
    debugPrintFunction=0x55555558f1cd <CServer::<lambda(char const*)>::_FUN(const char *)>) at /home/lighthouse/fastgit/libsm64/src/libsm64.c:104
#2  0x000055555558fc9f in CServer::Run (this=0x7ffff49f1010) at /home/lighthouse/fastgit/src/engine/server/server.cpp:2674
#3  0x000055555557584c in main (argc=1, argv=0x7fffffffe4f8) at /home/lighthouse/fastgit/src/engine/server/main.cpp:187

@headshot2017
